### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by khan202612** [ppxb/DouyinDownloader#1]
$ pnpm build:win

> douyindownloader@1.0.0 build:win C:\Users\love8\Downloads\DouyinDownloader
> npm run build && electron-builder --win --config

> douyindownloader@1.0.0 build
> npm run typecheck && electron-vite build

> douyindownloader@1.0.0 typecheck
> npm run typecheck:node && npm run typecheck:web

> douyindownloader@1.0.0 typecheck:node
> tsc --noEmit -p tsconfig.node.json --composite false

src/main/manager/index.ts(55,35): error TS6133: 'progressData' is declared but its value is never read.
 ELIFECYCLE  Command failed with exit code 2.
敢问大佬这是哪错误呢？

**Comment by ppxb** [comment]
该项目现处于积极开发阶段，任何平台的分发都未进行测试，代码结构极其不稳定。
建议现阶段使用开发模式调试。

**Comment by ppxb** [comment]
拉取最新代码并安装依赖可进行分发版本的构建，在 Windows 11 x64 下测试通过。
