### ISSUE TITLE
无法进行下载抖音视频

### ISSUE THREAD

**Issue by khan202612** [ppxb/DouyinDownloader#3]
问题操作步骤
1、编译成功生成安装包，安装后打开应用
2、设置cookie成功
3、随便找了一个视频：https://www.douyin.com/user/self?modal_id=7305311843449457946&showTab=like
4、新建下载任务
问题：
点击开始下载后，直接在已完成下显示，大小是0M
![image](https://github.com/ppxb/DouyinDownloader/assets/8869367/30342f8c-ffa2-41cb-97d4-32ae2cc25b3f)

**Comment by ppxb** [comment]
问题未复现。
![微信截图_20240112000925](https://github.com/ppxb/DouyinDownloader/assets/17081240/b3c45f9b-bdfc-4cd7-833f-b9a6008d5044)
![微信截图_20240112001011](https://github.com/ppxb/DouyinDownloader/assets/17081240/4c841776-5d96-46f7-942d-baf271e39c62)
![微信截图_20240112001032](https://github.com/ppxb/DouyinDownloader/assets/17081240/8b845d9e-7ef1-46a3-a23c-f1b0dd657f2a)

**Comment by ppxb** [comment]
请尽量使用 `pnpm start` 进行打包前预览。打包后，可以附加参数 `--trace-warnings`  到应用程序运行，查看错误信息。例如：`.\app.exe --trace-warnings`（在 Windows 中），`open app.app --args --trace-warnings`（在 MacOS 中）。
